### PR TITLE
Flicker fix

### PR DESCRIPTION
**Pull request by TylerBarnes**
Hey Nils,
The issue was the @font-face rule was being reloaded over and over endlessly in createGlobalStyles. I moved the font loading to a css file and put the fonts in the static folder and the flicker went away.

I'll have to do some tests and see if transition link is rerendering the layout component a bunch of times. I didn't see it doing that before but it looks like it may be. 

I also noticed the video.js component is rendering over and over again constantly even when the page isn't focused. It might be worth checking that out. It's probably not related to this though.

### CODE REVIEW

**Comment by nilsborg** [comment]
Man! Thank you so much!! really.. as i said i was going nuts about this :)

I'm just starting with react and gatsby .. more or less. But this is the first project with styled components. I thought this global styles thing was their way of including a css file.. Maybe it's actually worth checking if layout gets mounted multiple times.

Which brings me to a question i was always wondering about: how did u see that global styles getting injected all the time? Is there like a pro way of debugging stuff like this?

**Comment by TylerBarnes** [comment]
Actually it was pretty hard to debug since the problem only seems to happen in the production build. It seems in dev styled components knows not to reapply the global styles but maybe something is messed up in SSR somehow? I believe normally `createGlobalStyles` is supposed to be similar to including a global css file like you're thinking.
When I get some time I'll use this project to do a deeper debugging session if you don't mind.
The way I found the issue was when I ran `gatsby serve` and tried the site and then turned off `gatsby serve` but kept trying to use the site, I was getting a long list of errors where the site was repeatedly giving a 404 error trying to access the font files. 
Before I noticed this my debugging technique was to disable certain components to try to narrow down the scope of the bug. I just read the code and built a small mental model of what was coming from where and eventually noticed the issue.
For "pro" debugging make sure you're using [react dev-tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) if you're not already. Possibly the [React performance profiler](https://scotch.io/tutorials/use-the-react-profiler-for-performance) would've caught the issue but I actually didn't try using it haha.

**Comment by nilsborg** [comment]
Ah woow okok. 
React Dev tools I have (of course! :)) but the performance profiler looks cool.
I think moving to react is a pretty big paradigm shift.. at least I have to wrap my head around the fact, that I can and should let react to it's component updating etcetc.. 

> When I get some time I'll use this project to do a deeper debugging session if you don't mind.

Yes sure of course! Let me know if you find anything.

**Comment by nilsborg** [comment]
> I also noticed the video.js component is rendering over and over again constantly even when the page isn't focused. It might be worth checking that out. It's probably not related to this though.

Ah yes this thing: How did you notice that? Or better: what do you mean exactly? Like the video is still playing?

**Comment by TylerBarnes** [comment]
It was the same thing as the layout re-rendering, when I ran build && serve and then turned off serve but checked the console, I saw it trying to get the video file over and over again but 404'ing. I think it might be that it's tracking mouse events so it _should_ be re-rendering but maybe it needs to be throttled if it's not already? The weird part was to see it re-rendering when my mouse wasn't on the screen. It's not a huge deal since it seems to work fine but it might be worth checking in to! :)

**Comment by TylerBarnes** [comment]
You could also just add a console log to the render function to see how many times something is re-rendering. I didn't look into the video thing for more than a minute or so so it could actually be totally fine

**Comment by nilsborg** [comment]
I think that’s one of the things I don’t really get about react yet.. I’m animating the shadow on mouse move. The shadow is a div in the video component which gets style props. 
Then the actual video element is there too but if that gets re rendered (rendering = paint/layout?) all the time .. that would be terrible! :) like even if it works .. 

I guess coming from vanilla JS I think i apply styles to a div and that’s that. Like the other elements are not affected by that.. 

Looooong story short: I’ll dig into it and figure it out!

**Comment by TylerBarnes** [comment]
check out shouldComponentUpdate for that
https://reactjs.org/docs/optimizing-performance.html

If you don't want the whole component to rerender you can return false and then have a separate component that's rerendering inside of it I believe.

**Pull request merged**
